import = [
  # "~/.config/alacritty/catppuccin-macchiato.toml",
  "~/.config/alacritty/catppuccin-mocha.toml",
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[window]
padding = { x = 5, y = 5 }
opacity = 0.9
class = { instance = "Alacritty", general = "Alacritty" }

[scrolling]
history = 10000
multiplier = 3

[font]
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font Mono", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font Mono", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font Mono", style = "Bold Italic" }
size = 9.0

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#11121d"
foreground = "#a9b1d6"

[colors.normal]
black = "#32344a"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#ad8ee6"
cyan = "#449dab"
white = "#787c99"


[colors.bright]
black = "#444b6a"
red = "#ff7a93"
green = "#b9f27c"
yellow = "#ff9e64"
blue = "#7da6ff"
magenta = "#bb9af7"
cyan = "#0db9d7"
white = "#acb0d0"

[selection]
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Off" }
# blinking_interval = 750

[keyboard]
bindings = [
 { key = "Return", mods = "Super|Shift", action = "SpawnNewInstance" }
]

